import { StyleSheet, Platform } from 'react-native';

const isPad = Platform.OS === 'ios' && Platform.isPad;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  centerContainer: {
    flex: 1,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  camera: {
    flex: 1,
  },
  topHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 10,
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  appTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1e90ff',
    letterSpacing: 1,
  },
  flipButton: {
    padding: 12,
    backgroundColor: 'rgba(30,144,255,0.2)',
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(30,144,255,0.5)',
  },
  ttsToggle: {
    padding: 12,
    backgroundColor: 'rgba(30,144,255,0.08)',
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(30,144,255,0.3)',
    marginRight: 8,
  },
  modeContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.8)',
    borderRadius: 30,
    padding: 5,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    marginBottom: 15,
    marginHorizontal: 50,
  },
  modeTab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
    marginHorizontal: 2,
  },
  modeTabPad: {
    paddingVertical: 8,
    paddingHorizontal: 15,
  },
  modeTabActive: {
    backgroundColor: 'rgba(30,144,255,0.3)',
  },
  modeTabText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 6,
  },
  modeTabTextActive: {
    color: '#1e90ff',
  },
  countdownOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  flashOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'white',
    opacity: 0.8,
  },
  countdownDisplayLarge: {
    fontSize: 160,
    color: '#1e90ff',
    fontWeight: '900',
    textShadowColor: 'rgba(30,144,255,0.8)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 30,
  },
  recordingIndicator: {
    position: 'absolute',
    top: 120,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,0,0,0.8)',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
  },
  recordingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'white',
    marginRight: 8,
  },
  recordingText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  bottomControls: {
    backgroundColor: 'rgba(10,10,10,0.95)',
    paddingBottom: 30,
    paddingTop: 20,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    borderTopWidth: 1,
    borderTopColor: 'rgba(30,144,255,0.3)',
  },
  timerOptions: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    paddingHorizontal: 20,
    backgroundColor: 'rgba(30,144,255,0.1)',
    marginHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  timerLabel: {
    color: '#1e90ff',
    fontSize: 16,
    marginRight: 10,
    fontWeight: '600',
  },
  timerButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginHorizontal: 4,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  timerButtonSelected: {
    backgroundColor: '#1e90ff',
    borderColor: '#1e90ff',
    transform: [{ scale: 1.1 }],
  },
  timerText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 14,
    fontWeight: '500',
  },
  timerTextSelected: {
    color: 'white',
    fontWeight: '700',
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  galleryButton: {
    padding: 12,
    backgroundColor: 'rgba(30,144,255,0.1)',
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(30,144,255,0.3)',
  },
  captureButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(30,144,255,0.2)',
    padding: 4,
    borderWidth: 3,
    borderColor: '#1e90ff',
  },
  captureButtonInner: {
    flex: 1,
    borderRadius: 35,
    backgroundColor: '#1e90ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  captureCountdown: {
    fontSize: 26,
    fontWeight: 'bold',
    color: 'white',
  },
  videoButton: {
    backgroundColor: 'rgba(255,0,0,0.1)',
    borderWidth: 3,
    borderColor: '#ff4444',
  },
  videoButtonInner: {
    flex: 1,
    margin: 8,
    borderRadius: 30,
    backgroundColor: '#ff4444',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoButtonRecording: {
    backgroundColor: 'white',
    borderRadius: 10,
    margin: 12,
  },
  videoCountdown: {
    fontSize: 26,
    fontWeight: 'bold',
    color: 'white',
    textAlign: 'center',
  },
  quickActionButton: {
    padding: 10,
  },
  disabled: {
    opacity: 0.5,
  },
  text: {
    fontSize: 18,
    color: 'white',
  },
  captureText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  // Volume control styles
  topControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  volumeControl: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(30,144,255,0.08)',
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(30,144,255,0.3)',
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginRight: 8,
  },
  volumeIcon: {
    marginRight: 8,
  },
  volumeSlider: {
    width: 100,
    height: 40,
  },
  // Silent mode warning
  silentModeWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,107,107,0.9)',
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginHorizontal: 20,
    marginTop: 10,
    borderRadius: 10,
  },
  silentModeWarningText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
    flex: 1,
    marginLeft: 10,
  },
  silentModeClose: {
    padding: 5,
  },
  // iPad specific styles - more compact
  topHeaderPad: {
    paddingTop: 35,
    paddingHorizontal: 12,
    paddingBottom: 5,
  },
  appTitlePad: {
    fontSize: 18,
  },
  volumeControlPad: {
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  volumeSliderPad: {
    width: 70,
    height: 30,
  },
  flipButtonPad: {
    padding: 8,
  },
  bottomControlsPad: {
    paddingBottom: 15,
    paddingTop: 10,
  },
  modeContainerPad: {
    padding: 3,
    marginBottom: 8,
    marginHorizontal: 120,
  },
  modeTabTextPad: {
    fontSize: 11,
  },
  timerOptionsPad: {
    marginBottom: 10,
    paddingVertical: 6,
    marginHorizontal: 80,
  },
  timerLabelPad: {
    fontSize: 12,
  },
  timerButtonPad: {
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  timerTextPad: {
    fontSize: 11,
  },
  captureButtonPad: {
    width: 55,
    height: 55,
    borderRadius: 27.5,
    borderWidth: 2,
  },
});
